#if !PORTABLE
using System.Drawing.Pictograms.Attributes;
namespace System.Drawing.Pictograms
#else
using Xamarin.Forms.Pictograms.Attributes;
namespace Xamarin.Forms.Pictograms
#endif
{
    /// <summary>
    /// Ionic
    /// <see cref="http://ionicons.com/"/>
    /// </summary>
    [Pictogram("IonIcons", "ionicons", "https://github.com/driftyco/ionicons/archive/v2.0.1.zip")]
    public class IonIcons : Pictogram
    {

        #region Singleton

        /// <summary>
        /// Initializes the <see cref="Icon" /> class by loading the font from resources upon first use.
        /// </summary>
#if !PORTABLE

        private IonIcons() : base(Properties.Resources.ionicons)
#else

        private IonIcons() : base()
#endif
        {
        }

        internal static IonIcons instance;

        public static IonIcons Instance
        {
            get
            {
                if (instance == null)
                    instance = new IonIcons();
                return (IonIcons)instance;
            }
        }

        #endregion Singleton

        public IonIcons(bool @default) : this()
        {
        }
        
#if PORTABLE

        public override string GetFontFace()
        {
            return IonIcons.Typeface;
        }

#endif

        #region Statics

#if !PORTABLE

        public static Image GetImage(IconType type, int size, Brush brush)
        {
            return IonIcons.Instance.GetImage((int)type, size, brush);
        }

        public static Image GetImage(IconType type, int size, Color color)
        {
            return IonIcons.Instance.GetImage((int)type, size, color);
        }

        public static Image GetImage(IconType type, int size)
        {
            return IonIcons.Instance.GetImage((int)type, size);
        }

#endif

        public static string GetText(IconType type)
        {
            return char.ConvertFromUtf32((int)type);
        }

#if !PORTABLE

        public static new Font GetFont(float size, GraphicsUnit units = GraphicsUnit.Point)
        {
            return new Font(IonIcons.Instance.fonts.Families[0], size, units);
        }

#endif

        #endregion Statics

        /// <summary>
        /// Version 2.0.1
        /// </summary>
        public enum IconType : int
        {
            alert = 0xf101,
            alert_circled = 0xf100,
            android_add = 0xf2c7,
            android_add_circle = 0xf359,
            android_alarm_clock = 0xf35a,
            android_alert = 0xf35b,
            android_apps = 0xf35c,
            android_archive = 0xf2c9,
            android_arrow_back = 0xf2ca,
            android_arrow_down = 0xf35d,
            android_arrow_dropdown = 0xf35f,
            android_arrow_dropdown_circle = 0xf35e,
            android_arrow_dropleft = 0xf361,
            android_arrow_dropleft_circle = 0xf360,
            android_arrow_dropright = 0xf363,
            android_arrow_dropright_circle = 0xf362,
            android_arrow_dropup = 0xf365,
            android_arrow_dropup_circle = 0xf364,
            android_arrow_forward = 0xf30f,
            android_arrow_up = 0xf366,
            android_attach = 0xf367,
            android_bar = 0xf368,
            android_bicycle = 0xf369,
            android_boat = 0xf36a,
            android_bookmark = 0xf36b,
            android_bulb = 0xf36c,
            android_bus = 0xf36d,
            android_calendar = 0xf2d1,
            android_call = 0xf2d2,
            android_camera = 0xf2d3,
            android_cancel = 0xf36e,
            android_car = 0xf36f,
            android_cart = 0xf370,
            android_chat = 0xf2d4,
            android_checkbox = 0xf374,
            android_checkbox_blank = 0xf371,
            android_checkbox_outline = 0xf373,
            android_checkbox_outline_blank = 0xf372,
            android_checkmark_circle = 0xf375,
            android_clipboard = 0xf376,
            android_close = 0xf2d7,
            android_cloud = 0xf37a,
            android_cloud_circle = 0xf377,
            android_cloud_done = 0xf378,
            android_cloud_outline = 0xf379,
            android_color_palette = 0xf37b,
            android_compass = 0xf37c,
            android_contact = 0xf2d8,
            android_contacts = 0xf2d9,
            android_contract = 0xf37d,
            android_create = 0xf37e,
            android_delete = 0xf37f,
            android_desktop = 0xf380,
            android_document = 0xf381,
            android_done = 0xf383,
            android_done_all = 0xf382,
            android_download = 0xf2dd,
            android_drafts = 0xf384,
            android_exit = 0xf385,
            android_expand = 0xf386,
            android_favorite = 0xf388,
            android_favorite_outline = 0xf387,
            android_film = 0xf389,
            android_folder = 0xf2e0,
            android_folder_open = 0xf38a,
            android_funnel = 0xf38b,
            android_globe = 0xf38c,
            android_hand = 0xf2e3,
            android_hangout = 0xf38d,
            android_happy = 0xf38e,
            android_home = 0xf38f,
            android_image = 0xf2e4,
            android_laptop = 0xf390,
            android_list = 0xf391,
            android_locate = 0xf2e9,
            android_lock = 0xf392,
            android_mail = 0xf2eb,
            android_map = 0xf393,
            android_menu = 0xf394,
            android_microphone = 0xf2ec,
            android_microphone_off = 0xf395,
            android_more_horizontal = 0xf396,
            android_more_vertical = 0xf397,
            android_navigate = 0xf398,
            android_notifications = 0xf39b,
            android_notifications_none = 0xf399,
            android_notifications_off = 0xf39a,
            android_open = 0xf39c,
            android_options = 0xf39d,
            android_people = 0xf39e,
            android_person = 0xf3a0,
            android_person_add = 0xf39f,
            android_phone_landscape = 0xf3a1,
            android_phone_portrait = 0xf3a2,
            android_pin = 0xf3a3,
            android_plane = 0xf3a4,
            android_playstore = 0xf2f0,
            android_print = 0xf3a5,
            android_radio_button_off = 0xf3a6,
            android_radio_button_on = 0xf3a7,
            android_refresh = 0xf3a8,
            android_remove = 0xf2f4,
            android_remove_circle = 0xf3a9,
            android_restaurant = 0xf3aa,
            android_sad = 0xf3ab,
            android_search = 0xf2f5,
            android_send = 0xf2f6,
            android_settings = 0xf2f7,
            android_share = 0xf2f8,
            android_share_alt = 0xf3ac,
            android_star = 0xf2fc,
            android_star_half = 0xf3ad,
            android_star_outline = 0xf3ae,
            android_stopwatch = 0xf2fd,
            android_subway = 0xf3af,
            android_sunny = 0xf3b0,
            android_sync = 0xf3b1,
            android_textsms = 0xf3b2,
            android_time = 0xf3b3,
            android_train = 0xf3b4,
            android_unlock = 0xf3b5,
            android_upload = 0xf3b6,
            android_volume_down = 0xf3b7,
            android_volume_mute = 0xf3b8,
            android_volume_off = 0xf3b9,
            android_volume_up = 0xf3ba,
            android_walk = 0xf3bb,
            android_warning = 0xf3bc,
            android_watch = 0xf3bd,
            android_wifi = 0xf305,
            aperture = 0xf313,
            archive = 0xf102,
            arrow_down_a = 0xf103,
            arrow_down_b = 0xf104,
            arrow_down_c = 0xf105,
            arrow_expand = 0xf25e,
            arrow_graph_down_left = 0xf25f,
            arrow_graph_down_right = 0xf260,
            arrow_graph_up_left = 0xf261,
            arrow_graph_up_right = 0xf262,
            arrow_left_a = 0xf106,
            arrow_left_b = 0xf107,
            arrow_left_c = 0xf108,
            arrow_move = 0xf263,
            arrow_resize = 0xf264,
            arrow_return_left = 0xf265,
            arrow_return_right = 0xf266,
            arrow_right_a = 0xf109,
            arrow_right_b = 0xf10a,
            arrow_right_c = 0xf10b,
            arrow_shrink = 0xf267,
            arrow_swap = 0xf268,
            arrow_up_a = 0xf10c,
            arrow_up_b = 0xf10d,
            arrow_up_c = 0xf10e,
            asterisk = 0xf314,
            at = 0xf10f,
            backspace = 0xf3bf,
            backspace_outline = 0xf3be,
            bag = 0xf110,
            battery_charging = 0xf111,
            battery_empty = 0xf112,
            battery_full = 0xf113,
            battery_half = 0xf114,
            battery_low = 0xf115,
            beaker = 0xf269,
            beer = 0xf26a,
            bluetooth = 0xf116,
            bonfire = 0xf315,
            bookmark = 0xf26b,
            bowtie = 0xf3c0,
            briefcase = 0xf26c,
            bug = 0xf2be,
            calculator = 0xf26d,
            calendar = 0xf117,
            camera = 0xf118,
            card = 0xf119,
            cash = 0xf316,
            chatbox = 0xf11b,
            chatbox_working = 0xf11a,
            chatboxes = 0xf11c,
            chatbubble = 0xf11e,
            chatbubble_working = 0xf11d,
            chatbubbles = 0xf11f,
            checkmark = 0xf122,
            checkmark_circled = 0xf120,
            checkmark_round = 0xf121,
            chevron_down = 0xf123,
            chevron_left = 0xf124,
            chevron_right = 0xf125,
            chevron_up = 0xf126,
            clipboard = 0xf127,
            clock = 0xf26e,
            close = 0xf12a,
            close_circled = 0xf128,
            close_round = 0xf129,
            closed_captioning = 0xf317,
            cloud = 0xf12b,
            code = 0xf271,
            code_download = 0xf26f,
            code_working = 0xf270,
            coffee = 0xf272,
            compass = 0xf273,
            compose = 0xf12c,
            connection_bars = 0xf274,
            contrast = 0xf275,
            crop = 0xf3c1,
            cube = 0xf318,
            disc = 0xf12d,
            document = 0xf12f,
            document_text = 0xf12e,
            drag = 0xf130,
            earth = 0xf276,
            easel = 0xf3c2,
            edit = 0xf2bf,
            egg = 0xf277,
            eject = 0xf131,
            email = 0xf132,
            email_unread = 0xf3c3,
            erlenmeyer_flask = 0xf3c5,
            erlenmeyer_flask_bubbles = 0xf3c4,
            eye = 0xf133,
            eye_disabled = 0xf306,
            female = 0xf278,
            filing = 0xf134,
            film_marker = 0xf135,
            fireball = 0xf319,
            flag = 0xf279,
            flame = 0xf31a,
            flash = 0xf137,
            flash_off = 0xf136,
            folder = 0xf139,
            fork = 0xf27a,
            fork_repo = 0xf2c0,
            forward = 0xf13a,
            funnel = 0xf31b,
            gear_a = 0xf13d,
            gear_b = 0xf13e,
            grid = 0xf13f,
            hammer = 0xf27b,
            happy = 0xf31c,
            happy_outline = 0xf3c6,
            headphone = 0xf140,
            heart = 0xf141,
            heart_broken = 0xf31d,
            help = 0xf143,
            help_buoy = 0xf27c,
            help_circled = 0xf142,
            home = 0xf144,
            icecream = 0xf27d,
            image = 0xf147,
            images = 0xf148,
            information = 0xf14a,
            information_circled = 0xf149,
            ionic = 0xf14b,
            ios_alarm = 0xf3c8,
            ios_alarm_outline = 0xf3c7,
            ios_albums = 0xf3ca,
            ios_albums_outline = 0xf3c9,
            ios_americanfootball = 0xf3cc,
            ios_americanfootball_outline = 0xf3cb,
            ios_analytics = 0xf3ce,
            ios_analytics_outline = 0xf3cd,
            ios_arrow_back = 0xf3cf,
            ios_arrow_down = 0xf3d0,
            ios_arrow_forward = 0xf3d1,
            ios_arrow_left = 0xf3d2,
            ios_arrow_right = 0xf3d3,
            ios_arrow_thin_down = 0xf3d4,
            ios_arrow_thin_left = 0xf3d5,
            ios_arrow_thin_right = 0xf3d6,
            ios_arrow_thin_up = 0xf3d7,
            ios_arrow_up = 0xf3d8,
            ios_at = 0xf3da,
            ios_at_outline = 0xf3d9,
            ios_barcode = 0xf3dc,
            ios_barcode_outline = 0xf3db,
            ios_baseball = 0xf3de,
            ios_baseball_outline = 0xf3dd,
            ios_basketball = 0xf3e0,
            ios_basketball_outline = 0xf3df,
            ios_bell = 0xf3e2,
            ios_bell_outline = 0xf3e1,
            ios_body = 0xf3e4,
            ios_body_outline = 0xf3e3,
            ios_bolt = 0xf3e6,
            ios_bolt_outline = 0xf3e5,
            ios_book = 0xf3e8,
            ios_book_outline = 0xf3e7,
            ios_bookmarks = 0xf3ea,
            ios_bookmarks_outline = 0xf3e9,
            ios_box = 0xf3ec,
            ios_box_outline = 0xf3eb,
            ios_briefcase = 0xf3ee,
            ios_briefcase_outline = 0xf3ed,
            ios_browsers = 0xf3f0,
            ios_browsers_outline = 0xf3ef,
            ios_calculator = 0xf3f2,
            ios_calculator_outline = 0xf3f1,
            ios_calendar = 0xf3f4,
            ios_calendar_outline = 0xf3f3,
            ios_camera = 0xf3f6,
            ios_camera_outline = 0xf3f5,
            ios_cart = 0xf3f8,
            ios_cart_outline = 0xf3f7,
            ios_chatboxes = 0xf3fa,
            ios_chatboxes_outline = 0xf3f9,
            ios_chatbubble = 0xf3fc,
            ios_chatbubble_outline = 0xf3fb,
            ios_checkmark = 0xf3ff,
            ios_checkmark_empty = 0xf3fd,
            ios_checkmark_outline = 0xf3fe,
            ios_circle_filled = 0xf400,
            ios_circle_outline = 0xf401,
            ios_clock = 0xf403,
            ios_clock_outline = 0xf402,
            ios_close = 0xf406,
            ios_close_empty = 0xf404,
            ios_close_outline = 0xf405,
            ios_cloud = 0xf40c,
            ios_cloud_download = 0xf408,
            ios_cloud_download_outline = 0xf407,
            ios_cloud_outline = 0xf409,
            ios_cloud_upload = 0xf40b,
            ios_cloud_upload_outline = 0xf40a,
            ios_cloudy = 0xf410,
            ios_cloudy_night = 0xf40e,
            ios_cloudy_night_outline = 0xf40d,
            ios_cloudy_outline = 0xf40f,
            ios_cog = 0xf412,
            ios_cog_outline = 0xf411,
            ios_color_filter = 0xf414,
            ios_color_filter_outline = 0xf413,
            ios_color_wand = 0xf416,
            ios_color_wand_outline = 0xf415,
            ios_compose = 0xf418,
            ios_compose_outline = 0xf417,
            ios_contact = 0xf41a,
            ios_contact_outline = 0xf419,
            ios_copy = 0xf41c,
            ios_copy_outline = 0xf41b,
            ios_crop = 0xf41e,
            ios_crop_strong = 0xf41d,
            ios_download = 0xf420,
            ios_download_outline = 0xf41f,
            ios_drag = 0xf421,
            ios_email = 0xf423,
            ios_email_outline = 0xf422,
            ios_eye = 0xf425,
            ios_eye_outline = 0xf424,
            ios_fastforward = 0xf427,
            ios_fastforward_outline = 0xf426,
            ios_filing = 0xf429,
            ios_filing_outline = 0xf428,
            ios_film = 0xf42b,
            ios_film_outline = 0xf42a,
            ios_flag = 0xf42d,
            ios_flag_outline = 0xf42c,
            ios_flame = 0xf42f,
            ios_flame_outline = 0xf42e,
            ios_flask = 0xf431,
            ios_flask_outline = 0xf430,
            ios_flower = 0xf433,
            ios_flower_outline = 0xf432,
            ios_folder = 0xf435,
            ios_folder_outline = 0xf434,
            ios_football = 0xf437,
            ios_football_outline = 0xf436,
            ios_game_controller_a = 0xf439,
            ios_game_controller_a_outline = 0xf438,
            ios_game_controller_b = 0xf43b,
            ios_game_controller_b_outline = 0xf43a,
            ios_gear = 0xf43d,
            ios_gear_outline = 0xf43c,
            ios_glasses = 0xf43f,
            ios_glasses_outline = 0xf43e,
            ios_grid_view = 0xf441,
            ios_grid_view_outline = 0xf440,
            ios_heart = 0xf443,
            ios_heart_outline = 0xf442,
            ios_help = 0xf446,
            ios_help_empty = 0xf444,
            ios_help_outline = 0xf445,
            ios_home = 0xf448,
            ios_home_outline = 0xf447,
            ios_infinite = 0xf44a,
            ios_infinite_outline = 0xf449,
            ios_information = 0xf44d,
            ios_information_empty = 0xf44b,
            ios_information_outline = 0xf44c,
            ios_ionic_outline = 0xf44e,
            ios_keypad = 0xf450,
            ios_keypad_outline = 0xf44f,
            ios_lightbulb = 0xf452,
            ios_lightbulb_outline = 0xf451,
            ios_list = 0xf454,
            ios_list_outline = 0xf453,
            ios_location = 0xf456,
            ios_location_outline = 0xf455,
            ios_locked = 0xf458,
            ios_locked_outline = 0xf457,
            ios_loop = 0xf45a,
            ios_loop_strong = 0xf459,
            ios_medical = 0xf45c,
            ios_medical_outline = 0xf45b,
            ios_medkit = 0xf45e,
            ios_medkit_outline = 0xf45d,
            ios_mic = 0xf461,
            ios_mic_off = 0xf45f,
            ios_mic_outline = 0xf460,
            ios_minus = 0xf464,
            ios_minus_empty = 0xf462,
            ios_minus_outline = 0xf463,
            ios_monitor = 0xf466,
            ios_monitor_outline = 0xf465,
            ios_moon = 0xf468,
            ios_moon_outline = 0xf467,
            ios_more = 0xf46a,
            ios_more_outline = 0xf469,
            ios_musical_note = 0xf46b,
            ios_musical_notes = 0xf46c,
            ios_navigate = 0xf46e,
            ios_navigate_outline = 0xf46d,
            ios_nutrition = 0xf470,
            ios_nutrition_outline = 0xf46f,
            ios_paper = 0xf472,
            ios_paper_outline = 0xf471,
            ios_paperplane = 0xf474,
            ios_paperplane_outline = 0xf473,
            ios_partlysunny = 0xf476,
            ios_partlysunny_outline = 0xf475,
            ios_pause = 0xf478,
            ios_pause_outline = 0xf477,
            ios_paw = 0xf47a,
            ios_paw_outline = 0xf479,
            ios_people = 0xf47c,
            ios_people_outline = 0xf47b,
            ios_person = 0xf47e,
            ios_person_outline = 0xf47d,
            ios_personadd = 0xf480,
            ios_personadd_outline = 0xf47f,
            ios_photos = 0xf482,
            ios_photos_outline = 0xf481,
            ios_pie = 0xf484,
            ios_pie_outline = 0xf483,
            ios_pint = 0xf486,
            ios_pint_outline = 0xf485,
            ios_play = 0xf488,
            ios_play_outline = 0xf487,
            ios_plus = 0xf48b,
            ios_plus_empty = 0xf489,
            ios_plus_outline = 0xf48a,
            ios_pricetag = 0xf48d,
            ios_pricetag_outline = 0xf48c,
            ios_pricetags = 0xf48f,
            ios_pricetags_outline = 0xf48e,
            ios_printer = 0xf491,
            ios_printer_outline = 0xf490,
            ios_pulse = 0xf493,
            ios_pulse_strong = 0xf492,
            ios_rainy = 0xf495,
            ios_rainy_outline = 0xf494,
            ios_recording = 0xf497,
            ios_recording_outline = 0xf496,
            ios_redo = 0xf499,
            ios_redo_outline = 0xf498,
            ios_refresh = 0xf49c,
            ios_refresh_empty = 0xf49a,
            ios_refresh_outline = 0xf49b,
            ios_reload = 0xf49d,
            ios_reverse_camera = 0xf49f,
            ios_reverse_camera_outline = 0xf49e,
            ios_rewind = 0xf4a1,
            ios_rewind_outline = 0xf4a0,
            ios_rose = 0xf4a3,
            ios_rose_outline = 0xf4a2,
            ios_search = 0xf4a5,
            ios_search_strong = 0xf4a4,
            ios_settings = 0xf4a7,
            ios_settings_strong = 0xf4a6,
            ios_shuffle = 0xf4a9,
            ios_shuffle_strong = 0xf4a8,
            ios_skipbackward = 0xf4ab,
            ios_skipbackward_outline = 0xf4aa,
            ios_skipforward = 0xf4ad,
            ios_skipforward_outline = 0xf4ac,
            ios_snowy = 0xf4ae,
            ios_speedometer = 0xf4b0,
            ios_speedometer_outline = 0xf4af,
            ios_star = 0xf4b3,
            ios_star_half = 0xf4b1,
            ios_star_outline = 0xf4b2,
            ios_stopwatch = 0xf4b5,
            ios_stopwatch_outline = 0xf4b4,
            ios_sunny = 0xf4b7,
            ios_sunny_outline = 0xf4b6,
            ios_telephone = 0xf4b9,
            ios_telephone_outline = 0xf4b8,
            ios_tennisball = 0xf4bb,
            ios_tennisball_outline = 0xf4ba,
            ios_thunderstorm = 0xf4bd,
            ios_thunderstorm_outline = 0xf4bc,
            ios_time = 0xf4bf,
            ios_time_outline = 0xf4be,
            ios_timer = 0xf4c1,
            ios_timer_outline = 0xf4c0,
            ios_toggle = 0xf4c3,
            ios_toggle_outline = 0xf4c2,
            ios_trash = 0xf4c5,
            ios_trash_outline = 0xf4c4,
            ios_undo = 0xf4c7,
            ios_undo_outline = 0xf4c6,
            ios_unlocked = 0xf4c9,
            ios_unlocked_outline = 0xf4c8,
            ios_upload = 0xf4cb,
            ios_upload_outline = 0xf4ca,
            ios_videocam = 0xf4cd,
            ios_videocam_outline = 0xf4cc,
            ios_volume_high = 0xf4ce,
            ios_volume_low = 0xf4cf,
            ios_wineglass = 0xf4d1,
            ios_wineglass_outline = 0xf4d0,
            ios_world = 0xf4d3,
            ios_world_outline = 0xf4d2,
            ipad = 0xf1f9,
            iphone = 0xf1fa,
            ipod = 0xf1fb,
            jet = 0xf295,
            key = 0xf296,
            knife = 0xf297,
            laptop = 0xf1fc,
            leaf = 0xf1fd,
            levels = 0xf298,
            lightbulb = 0xf299,
            link = 0xf1fe,
            load_a = 0xf29a,
            load_b = 0xf29b,
            load_c = 0xf29c,
            load_d = 0xf29d,
            location = 0xf1ff,
            lock_combination = 0xf4d4,
            locked = 0xf200,
            log_in = 0xf29e,
            log_out = 0xf29f,
            loop = 0xf201,
            magnet = 0xf2a0,
            male = 0xf2a1,
            man = 0xf202,
            map = 0xf203,
            medkit = 0xf2a2,
            merge = 0xf33f,
            mic_a = 0xf204,
            mic_b = 0xf205,
            mic_c = 0xf206,
            minus = 0xf209,
            minus_circled = 0xf207,
            minus_round = 0xf208,
            model_s = 0xf2c1,
            monitor = 0xf20a,
            more = 0xf20b,
            mouse = 0xf340,
            music_note = 0xf20c,
            navicon = 0xf20e,
            navicon_round = 0xf20d,
            navigate = 0xf2a3,
            network = 0xf341,
            no_smoking = 0xf2c2,
            nuclear = 0xf2a4,
            outlet = 0xf342,
            paintbrush = 0xf4d5,
            paintbucket = 0xf4d6,
            paper_airplane = 0xf2c3,
            paperclip = 0xf20f,
            pause = 0xf210,
            person = 0xf213,
            person_add = 0xf211,
            person_stalker = 0xf212,
            pie_graph = 0xf2a5,
            pin = 0xf2a6,
            pinpoint = 0xf2a7,
            pizza = 0xf2a8,
            plane = 0xf214,
            planet = 0xf343,
            play = 0xf215,
            playstation = 0xf30a,
            plus = 0xf218,
            plus_circled = 0xf216,
            plus_round = 0xf217,
            podium = 0xf344,
            pound = 0xf219,
            power = 0xf2a9,
            pricetag = 0xf2aa,
            pricetags = 0xf2ab,
            printer = 0xf21a,
            pull_request = 0xf345,
            qr_scanner = 0xf346,
            quote = 0xf347,
            radio_waves = 0xf2ac,
            record = 0xf21b,
            refresh = 0xf21c,
            reply = 0xf21e,
            reply_all = 0xf21d,
            ribbon_a = 0xf348,
            ribbon_b = 0xf349,
            sad = 0xf34a,
            sad_outline = 0xf4d7,
            scissors = 0xf34b,
            search = 0xf21f,
            settings = 0xf2ad,
            share = 0xf220,
            shuffle = 0xf221,
            skip_backward = 0xf222,
            skip_forward = 0xf223,
            social_android = 0xf225,
            social_android_outline = 0xf224,
            social_angular = 0xf4d9,
            social_angular_outline = 0xf4d8,
            social_apple = 0xf227,
            social_apple_outline = 0xf226,
            social_bitcoin = 0xf2af,
            social_bitcoin_outline = 0xf2ae,
            social_buffer = 0xf229,
            social_buffer_outline = 0xf228,
            social_chrome = 0xf4db,
            social_chrome_outline = 0xf4da,
            social_codepen = 0xf4dd,
            social_codepen_outline = 0xf4dc,
            social_css3 = 0xf4df,
            social_css3_outline = 0xf4de,
            social_designernews = 0xf22b,
            social_designernews_outline = 0xf22a,
            social_dribbble = 0xf22d,
            social_dribbble_outline = 0xf22c,
            social_dropbox = 0xf22f,
            social_dropbox_outline = 0xf22e,
            social_euro = 0xf4e1,
            social_euro_outline = 0xf4e0,
            social_facebook = 0xf231,
            social_facebook_outline = 0xf230,
            social_foursquare = 0xf34d,
            social_foursquare_outline = 0xf34c,
            social_freebsd_devil = 0xf2c4,
            social_github = 0xf233,
            social_github_outline = 0xf232,
            social_google = 0xf34f,
            social_google_outline = 0xf34e,
            social_googleplus = 0xf235,
            social_googleplus_outline = 0xf234,
            social_hackernews = 0xf237,
            social_hackernews_outline = 0xf236,
            social_html5 = 0xf4e3,
            social_html5_outline = 0xf4e2,
            social_instagram = 0xf351,
            social_instagram_outline = 0xf350,
            social_javascript = 0xf4e5,
            social_javascript_outline = 0xf4e4,
            social_linkedin = 0xf239,
            social_linkedin_outline = 0xf238,
            social_markdown = 0xf4e6,
            social_nodejs = 0xf4e7,
            social_octocat = 0xf4e8,
            social_pinterest = 0xf2b1,
            social_pinterest_outline = 0xf2b0,
            social_python = 0xf4e9,
            social_reddit = 0xf23b,
            social_reddit_outline = 0xf23a,
            social_rss = 0xf23d,
            social_rss_outline = 0xf23c,
            social_sass = 0xf4ea,
            social_skype = 0xf23f,
            social_skype_outline = 0xf23e,
            social_snapchat = 0xf4ec,
            social_snapchat_outline = 0xf4eb,
            social_tumblr = 0xf241,
            social_tumblr_outline = 0xf240,
            social_tux = 0xf2c5,
            social_twitch = 0xf4ee,
            social_twitch_outline = 0xf4ed,
            social_twitter = 0xf243,
            social_twitter_outline = 0xf242,
            social_usd = 0xf353,
            social_usd_outline = 0xf352,
            social_vimeo = 0xf245,
            social_vimeo_outline = 0xf244,
            social_whatsapp = 0xf4f0,
            social_whatsapp_outline = 0xf4ef,
            social_windows = 0xf247,
            social_windows_outline = 0xf246,
            social_wordpress = 0xf249,
            social_wordpress_outline = 0xf248,
            social_yahoo = 0xf24b,
            social_yahoo_outline = 0xf24a,
            social_yen = 0xf4f2,
            social_yen_outline = 0xf4f1,
            social_youtube = 0xf24d,
            social_youtube_outline = 0xf24c,
            soup_can = 0xf4f4,
            soup_can_outline = 0xf4f3,
            speakerphone = 0xf2b2,
            speedometer = 0xf2b3,
            spoon = 0xf2b4,
            star = 0xf24e,
            stats_bars = 0xf2b5,
            steam = 0xf30b,
            stop = 0xf24f,
            thermometer = 0xf2b6,
            thumbsdown = 0xf250,
            thumbsup = 0xf251,
            toggle = 0xf355,
            toggle_filled = 0xf354,
            transgender = 0xf4f5,
            trash_a = 0xf252,
            trash_b = 0xf253,
            trophy = 0xf356,
            tshirt = 0xf4f7,
            tshirt_outline = 0xf4f6,
            umbrella = 0xf2b7,
            university = 0xf357,
            unlocked = 0xf254,
            upload = 0xf255,
            usb = 0xf2b8,
            videocamera = 0xf256,
            volume_high = 0xf257,
            volume_low = 0xf258,
            volume_medium = 0xf259,
            volume_mute = 0xf25a,
            wand = 0xf358,
            waterdrop = 0xf25b,
            wifi = 0xf25c,
            wineglass = 0xf2b9,
            woman = 0xf25d,
            wrench = 0xf2ba,
            xbox = 0xf30c,
        }
    }
}